version: '3.4' # specify docker-compose version

# Define the services/containers to be run
services:
  api:
    build:
      context: '.'
      target: development
    ports:
      - "8000:8000" # specify port forwarding
